### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by fundon** [abe33/atom-minimap-selection#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.3
**Thrown From**: [minimap-selection](https://github.com/abe33/atom-minimap-selection) package, v3.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /Users/fundon/.atom/packages/minimap-selection/lib/minimap-selection.coffee:40

TypeError: Cannot read property 'dispose' of undefined
  at Object.module.exports.deactivatePlugin (/Users/fundon/.atom/packages/minimap-selection/lib/minimap-selection.coffee:40:18)
  at Main.module.exports.PluginManagement.deactivateAllPlugins (/Users/fundon/.atom/packages/minimap/lib/mixins/plugin-management.coffee:104:12)
  at Main.deactivate (/Users/fundon/.atom/packages/minimap/lib/main.coffee:108:6)
  at Main.toggle (/Users/fundon/.atom/packages/minimap/lib/main.coffee:132:8)
  at atom-workspace.Main.activate.subscriptions.add.atom.commands.add.minimap:toggle (/Users/fundon/.atom/packages/minimap/lib/main.coffee:101:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.__bind [as handleCommandEvent] (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
  2x -0:03.4 minimap:toggle (atom-text-editor.editor.is-focused.vim-mode.command-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "minimap-git-diff",
      "minimap-find-and-replace",
      "minimap-color-highlight"
    ]
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.1.0
minimap-highlight-selected, v4.0.0
minimap-selection, v3.1.1
seti-ui, v0.6.3
vim-mode, v0.30.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Thanks for the report I'll take a look at that later.

**Comment by 190n** [comment]
I got this when I tried to disable the selection. It wasn't working so I tried to disable and then enable it.
